### PR TITLE
Support table completion for TRUNCATE

### PR DESCRIPTION
**Pull request by drocco007**

### CODE REVIEW

**Comment by drocco007** [comment]
Weird. The tests pass locally but fail on Travis. I'll have to look at it tomorrow… >,<

**Comment by amjith** [comment]
I've been struggling with that myself. Even before your PR, it was showing that behavior. :(

**Comment by darikg** [comment]
Looks like the failures are due to a difference between sqlparse 0.1.14 and 0.1.15. setup.py has >= 0.1.14 so it was passing on your machine with 14 and failing on travis with 15. I think this is related to a PR I made for sqlparse so I'll look into whether this is a bug in sqlparse or just out-of-date tests in pgcli.

**Comment by darikg** [comment]
Ok, the failures are totally unrelated to this PR. They reflect a pretty cosmetic problem as far as pgcli is concerned, in that they don't affect any of the sql completion. See andialbrecht/sqlparse#185

**Comment by amjith** [comment]
@drocco007 The changes look good. I'm happy to merge. But a test would be nice. Let me know if you don't have time and I'll whip one up. 

:custard:

**Comment by drocco007** [comment]
Sure thing! I'll put some tests together this evening (or tomorrow at the
latest).

**Comment by drocco007** [comment]
I have added some tests for all the code paths around this change. Please let me know how they look!

**Comment by amjith** [comment]
Tests look great! 

Thank you!! :ice_cream:

**Pull request merged**
