### PR TITLE
Interpret incoming JSON as a string instead of via json.loads

### LINKED ISSUE #163: JSON display shows u"..."
When `pgcli` is run in Python 2, JSON fields (`json` and `jsonb` types in PostgreSQL), are shown with `u"..."` prefixes for strings. I guess this is a side-effect of using `repr()`. Maybe the `pprint` module can be leveraged instead?

### PR DESCRIPTION
**Pull request by drocco007**
Replace the default JSON (and JSONB, if defined) type casters with versions that handle the incoming data as strings instead of via json.loads. This fixes #163 and makes JSON render the same way in pgcli as it does in psql. The typecaster uses the current connection's encoding — which defaults to the database encoding — to interpret the incoming data; the implementation should continue to behave correctly if someone ever adds the ability to change the client encoding to pgcli.

I tested this against 9.3 and 9.4 servers (yay Docker!).

Comments welcome. :)

### CODE REVIEW

**Comment by drocco007** [comment]
Hmm. The build is failing because the test server's database doesn't have the JSON types. I'll adjust the skip conditions on those tests to check that the server has the types defined, which would also let anyone who installed the types via an extension run the tests as well.

**Comment by drocco007** [comment]
OK, it passes Travis! :smiley:

**Comment by amjith** [comment]
Thank you for the PR to handle `json` types the right way. I appreciate the tests and the updates to make them pass in Travis. :)

There is one small corner case in the exception handling I commented about. Otherwise the change looks great!

:soccer:

**Comment by drocco007** [comment]
Done! Since the tests and the connection class used basically the same code, I made a common helper and eliminated some duplication.

**Comment by amjith** [comment]
Thank you! 

:cow2:

**Pull request merged**
