### PR TITLE
bugfix: make tables query schema filter match schematas query

### PR DESCRIPTION
**Pull request by darikg**
pgcli crashed for me today after making a new schema:

```
 File "C:\Users\dg\Anaconda3\envs\pgcli2\Scripts\pgcli-script.py", line 9, in <module>
    load_entry_point('pgcli==0.15.2', 'console_scripts', 'pgcli')()
  File "C:\Users\dg\Anaconda3\envs\pgcli2\lib\site-packages\click\core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dg\Anaconda3\envs\pgcli2\lib\site-packages\click\core.py", line 590, in main
    rv = self.invoke(ctx)
  File "C:\Users\dg\Anaconda3\envs\pgcli2\lib\site-packages\click\core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dg\Anaconda3\envs\pgcli2\lib\site-packages\click\core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "c:\users\dg\documents\python\pgcli\pgcli\main.py", line 331, in cli
    pgcli.run_cli()
  File "c:\users\dg\documents\python\pgcli\pgcli\main.py", line 250, in run_cli
    self.refresh_completions()
  File "c:\users\dg\documents\python\pgcli\pgcli\main.py", line 287, in refresh_completions
    completer.extend_tables(pgexecute.tables())
  File "c:\users\dg\documents\python\pgcli\pgcli\pgcompleter.py", line 106, in extend_tables
    self.dbmetadata['tables'][schema][table] = ['*']
KeyError: u'pg_temp_4'
```

This was my mistake from the schema PR

### CODE REVIEW

**Comment by amjith** [comment]
Is it possible to guard against the runtime failure by adding an except clause for the KeyError?

**Comment by darikg** [comment]
With the change in the tables query, this "shouldn't" happen again. I put the AttributeError catch in anyway as you suggested. Trade off is that might obfuscate any future insidious mistakes. Your call

**Comment by amjith** [comment]
> Trade off is that might obfuscate any future insidious mistakes.

Since you're logging the error message I think we can leave it in there for now. 

Looks good! I'll merge it in.

**Comment by amjith** [comment]
:custard:

**Pull request merged**
